### ISSUE TITLE
Mod says "You have run out of torches!" if they are in your off-hand slot

### ISSUE THREAD

**Issue by zontargs** [dimensionsintime/TorchPlaceMod#8]
If I have torches in my off-hand and not in my inventory, and right-click with a tool, the mod sends a chat message saying "You have run out of torches!". Maybe the mod should check whether there's torches in the off-hand slot, and not try to activate if they're there?

**Comment by dimensionsintime** [comment]
Confirmed. The mod was originally designed for people who don't use torches in their off hand, but I can see where this would be a problem. Just wrote this fix into the next version to be released shortly.

**Comment by dimensionsintime** [comment]
Fixed in new version 1.12.2-0.2
