### ISSUE TITLE
Torches dont get placed when using project e red morningstar

### ISSUE THREAD

**Issue by SpikeVanHellsing** [dimensionsintime/TorchPlaceMod#9]
Forge: 1.12.2 14.23.4.2745
Project E: 1.12-PE1.3.0
Torch Place Mod: 1.12.2-0.2

As the title states torches are not placed when right-clicking with a red morningstar from project e.

**Comment by dimensionsintime** [comment]
Checking the code on Github for ProjectE, I see that the star is set to non-repairable in the constructor. One of the stipulations of TorchPlaceMod is that the item used for clicking is a tool, and one of the measurements of checking if it's a tool is seeing if it's repairable. So, technically, this isn't a bug so I marked it "won'tfix". However, I will keep this in mind for a future update and maybe create a workaround for the config so you can whitelist "non-repairable" tools in the future.

**Comment by SpikeVanHellsing** [comment]
That would be cool. thank you.

**Comment by dimensionsintime** [comment]
Adding "non-tool" items that should place torches to the config file was added in latest version
